services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  # services:
  #   postfix:
  #     image: boky/postfix
  #     hostname: mail
  #     domainname: "elfstar.co.uk"
  #     ports::
  #       - "2525:25"

  # mailpit:
  #   image: axllent/mailpit
  #   ports:
  #     - "1025:1025"
  #     - "8025:2045"

  mysql:
    image: mysql:8.4
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql-data:

networks:
  laravel: